apiVersion: v1
kind: Service
metadata:
  name: wordpressdb-svc
  labels:
    app: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: wordpress
    tier: wordpressdb
  type: ClusterIP
  clusterIP: None
